title: Ben Nguyen
logo: docs/assets/1615587782223.jpg
description: Bilingual Data Scientist
Linkedin: https://www.linkedin.com/in/ben-nguyen-77a44832/
Gmail: nguyenben85@gmail.com
Ben
#show_downloads: true
theme: jekyll-theme-minimal

